[package]
name = "druid-test-quest"
version = "0.1.0"
authors = ["Justin Pfifer <justin.pfifer@carvana.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"